name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build Android AAR
      run: ./gradlew :shared:assembleRelease
    
    - name: Build iOS Frameworks
      run: ./gradlew :shared:linkReleaseFrameworkIosArm64 :shared:linkReleaseFrameworkIosX64 :shared:linkReleaseFrameworkIosSimulatorArm64
    
    - name: Create XCFramework
      run: |
        xcodebuild -create-xcframework \
          -framework shared/build/bin/iosArm64/releaseFramework/BingoSDK.framework \
          -framework shared/build/bin/iosX64/releaseFramework/BingoSDK.framework \
          -framework shared/build/bin/iosSimulatorArm64/releaseFramework/BingoSDK.framework \
          -output BingoSDK.xcframework
    
    - name: Zip XCFramework
      run: zip -r BingoSDK.xcframework.zip BingoSDK.xcframework
    
    - name: Calculate Checksum
      run: |
        CHECKSUM=$(swift package compute-checksum BingoSDK.xcframework.zip)
        echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV
        echo "Checksum: $CHECKSUM"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          shared/build/outputs/aar/shared-release.aar
          BingoSDK.xcframework.zip
        body: |
          ## Bingo SDK Release ${{ github.ref_name }}
          
          ### Android Integration
          ```kotlin
          repositories {
              maven { url = uri("https://jitpack.io") }
          }
          dependencies {
              implementation("com.github.yourusername:Bingo:${{ github.ref_name }}")
          }
          ```
          
          ### iOS Integration (Swift Package Manager)
          ```swift
          dependencies: [
              .package(url: "https://github.com/yourusername/Bingo.git", from: "${{ github.ref_name }}")
          ]
          ```
          
          ### iOS Integration (Manual)
          Download `BingoSDK.xcframework.zip` and add to your Xcode project.
          
          **XCFramework Checksum:** `${{ env.CHECKSUM }}`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
